name: fesaa_final_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

#---------------Packages-----------------#
dependencies:
  flutter:
    sdk: flutter

# utilty packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.5
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1

  

# icons
  iconsax: ^0.0.8 
  cupertino_icons: ^1.0.6

# State managment
  get: ^4.6.6
  get_storage: ^2.1.1  

# product spicfice
  google_fonts: ^6.2.1
 
# ------------------- ./ Packges End ----------------#
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

 
  uses-material-design: true

  #---------- Local Assets ------------------#

  assets:
    - assets/images/on_boarding_images/
    - assets/logos/
    - assets/icons/
    - assets/images/animations/
    - assets/images/banners/
    - assets/icons/categories/
    - assets/images/content/user.png
    - assets/images/services/
    - assets/icons/components/


